#!/usr/bin/env bash
BOLD="\033[1m"
BOLDB="\033[1;34m"
BOLDR="\033[1;31m"
BOLDG="\033[1;32m"
BOLDY="\033[1;33m"
NORMAL="\033[0m"
OK="${BOLDG}[OK]${NORMAL}"
ERR="${BOLDR}[ERR]${NORMAL}"
WRN="${BOLDY}[WRN]${NORMAL}"

CONFIG_HOME="${XDG_CONFIG_HOME:-HOME/.config/yapman}"
CACHE_HOME="${XDG_CACHE_HOME:-HOME/.cache/yapman}"
DATA_HOME="${XDG_DATA_HOME:-HOME/.local/share/yapman}"
YapmanConfigPath="${CONFIG_HOME}/yapman.conf"
YapmanCachePath="${CACHE_HOME}/"
YapmanPackagePath="${DATA_HOME}/packages"
YapmanLogsPath="${CACHE_HOME}/logs"
YapmanLogPath="${CACHE_HOME}/logs/yapman.log"
YapmanExampleConfigPath="${CONFIG_HOME}/yapman.d.conf"

AUR_DOMAIN="https://aur.archlinux.org"
AUR_BASE_URL="https://aur.archlinux.org/rpc/?v=5&type="
AUR_SEARCH_URL="${AUR_BASE_URL}search&arg="
AUR_INFO_URL="${AUR_BASE_URL}info&arg="

AUTHOR="@atahabaki"
PROGRAM="yapman"
VERSION="2.0.1"
ABBR="Yet Another Package Manager for AUR"
